apiVersion: v1
kind: Service
metadata:
  name: ld-balancer
  labels:
    app: tcmotd
spec:
  selector:
    app: tcmotd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
